---

- name: restart postfix
  systemd:
    name: postfix
    daemon_reload: true
    enabled: true
    state: started

- name: reload kernel parameters
  command: sysctl --load=/etc/sysctl.d/99-sysctl.conf

- name: restart network
  service:
    name: network
    state: restarted

