---

- name: restart postfix
  systemd:
    name: postfix
    daemon_reload: true
    enabled: true
    state: started

- name: reload kernel parameters
  command: sysctl --load=/etc/sysctl.d/99-sysctl.conf

- name: restart network
  service:
    name: network
    state: restarted

- name: restart sshd
  debug:
    msg: "checking /etc/ssh/sshd_config first"
  changed_when: true
  notify:
    - check sshd configuration
    - restart sshd - after config check

- name: check sshd configuration
  command: '/usr/sbin/sshd -t'
  register: sshd_config
  changed_when: "sshd_config.rc != 0"

- name: restart sshd - after config check
  service:
    name: sshd
    state: restarted
