---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  ssh_connection_options:
    - '-o IdentityFile=~/.vagrant.d/insecure_private_key'
lint:
  name: yamllint
platforms:
  - name: centos7h
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
