---
- name: Comply to CIS, but skip bugs.
  hosts: all
  become: true
  vars:
    mydomain: github.com
    manage_password_compliance: false
    pam_manage: false
  roles:
    - role: dockpack.base_epel
    - role: hardened7
