---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Install EPEL
      yum:
        name: epel-release
        state: present

  roles:
    - role: base_common
